import type { Metadata } from "next";
import { Inter } from "next/font/google";

import NavMenu from "@/components/NavMenu/NavMenu";

import "./globals.css";
import AuthProvider from "./AuthProvider";
import { SignInButton } from "@/components/AccountButtons/AccountButtons";
import { getServerSession } from "next-auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Homepage",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <AuthProvider>
    <html lang="en">
      <body className={inter.className}>
        <NavMenu />
        {children}
      </body>
    </html>
    </AuthProvider>
  );
}
